### ISSUE TITLE
Running over everything is kinda slow -- can we pass a list of files? (or globs?)

### ISSUE THREAD

**Issue by NullVoxPopuli** [mansona/lint-to-the-future#16]
In the project where I'm testing out lint-to-the-future, I have (relevant to eslint):
  ~ 19k JS files
  ~ 1.4k JSON files
  ~ 4k TS files
 
 _but_, the files where I _know_ have issue 
via [the silver searcher](https://github.com/ggreer/the_silver_searcher)'s `ag "the thing I'm linting against" --files-with-matches | wc -l ` (to list all the files that need to have lints disabled) runs in 2.8s.

After 7m30s, I `CTRL+C`'d `lint-to-thefuture ignore`

**Comment by NullVoxPopuli** [comment]
related: https://github.com/mansona/lint-to-the-future-eslint/issues/4

**Comment by mansona** [comment]
so we recently added a filter to the new remove command 🤔 I guess we could do the same to the ignore command if you wanted?
