### ISSUE TITLE
Document dashboard feature

### ISSUE THREAD

**Issue by ctjhoa** [mansona/lint-to-the-future#20]
This EmberFest video https://www.youtube.com/watch?v=GI7VEfrhdjo mentioned a dashboard feature with `lint-to-the-future`. 
According to https://github.com/mansona/lint-to-the-future-dashboard-action it seems to be driven by the `-o` option  but I cannot find documentation on it.
Can you provide steps to get that Dashboard or add documentation please?

**Comment by mansona** [comment]
This was finally added 🎉 https://github.com/mansona/lint-to-the-future#lint-to-the-future-dashboard

let me know what you think 👍
