### ISSUE TITLE
ignore cli command is broken

### ISSUE THREAD

**Issue by dagroe** [mansona/lint-to-the-future#64]
Running `lint-to-the-future ignore` fails.

The command passes an object as `cwd` to `ignoreAll` in `lint-to-the-future-eslint` here:
```js
return plugin.import.ignoreAll({filter: options.filter});
```

But that crashes when running `const currentPackageJSON = require(join(cwd, 'package.json'));` since `join` expects `string`s.

**Comment by mansona** [comment]
@dagroe what version of lint-to-the-future are you on? That was a known issue that was fixed in https://github.com/mansona/lint-to-the-future/pull/55 which was released in `v2.4.1`

**Comment by dagroe** [comment]
@mansona sorry, I ran it via `npx` assuming it would fetch the latest version but it used `2.4.0` from my `package.json`.
